//console.log("Hello world");
//let massage=("Hello World");
//console.log(massage);
//massage = "ABC"
//console.log(massage);
// const massage = ("HELLO WORLD");
// console.log(massage);
// let fullName = "Roofan John";
// console.log("hello");
// // console.log(fullName);
// let fullName = "Khurram Shahzad";
// let age = 23;
// let isMerried = true;
// let lastName: string = "Shahzad";
// let num1 = "1";
// let num2 = "2";
// console.log(num1 + num2);
// let result = num1 + num2;
// console.log(num1 + num2);
// console.log(num1);
// console.log(result);
var num1 = 3;
var num2 = 10;
console.log(num1 + num2);
console.log(num1 - num2);
console.log(num1 * num2);
console.log(num2 / num1);
console.log(num1 % num2);
console.log(Math.pow(num2, num1));
